FROM debian:jessie-slim

RUN apt update && apt install -y \
    libnetcdf-dev

# build passes --build-arg DONTCACHE=$(date) to keep the steps below from being cached
ARG DONTCACHE=1

RUN mkdir /data
WORKDIR /server
COPY ./target/release/elevation-api /server
COPY static/ /server/static/
COPY templates/ /server/templates/
RUN chmod +x /server/elevation-api

CMD /server/elevation-api run-server /data/